site_name: Documentação CBF 2025

nav:
  - Home: index.md
  - Convenção de Pontos: "Convencao de Pontos do Ranking Nacional dos Clubes do Futebol Feminino.md"
  - Diretriz Técnica 2025: "DIRETRIZ TECNICA 2025.md"
  - PGA – Feminino A1 2025: "PGA - Brasileiro Feminino A1 2025.md"
  - PGA – Série A 2025: "PGA - Brasileiro Serie A 2025.md"
  - PGA Compilado 2025: "PGA_2025_Compilado.md"
  - PGA Geral: "PGA.md"
  - Ranking 2025: "Ranking2025.md"
  - Rankings CBF 2025 (Completo Separado): "Rankings_CBF_2025_Completo_Separado.md"
  - REC – Feminino A3 2025: "REC - Brasileiro Feminino A3 2025.md"
  - REC – Masculino Série A Sub-20 2025: "REC - Brasileiro MASCULINO Serie A SUB-20 2025.md"
  - REC – Masculino Série B Sub-20 2025: "REC - Brasileiro MASCULINO Serie B SUB-20 2025.md"
  - REC – Série A 2025: "REC - Brasileiro Serie A 2025.md"
  - REC – Série B 2025: "REC - Brasileiro Serie B 2025.md"
  - REC – Série C 2025: "REC - Brasileiro Serie C 2025.md"
  - REC – Série D 2025: "REC - Brasileiro Serie D 2025.md"
  - REC – Copa do Brasil 2025: "REC - COPA DO BRASIL 2025.md"
  - REC – Copa do Brasil Masculina Sub-17 2025: "REC - COPA DO BRASIL MASCULINA SUB-17 2025.md"
  - REC – Copa do Nordeste 2025: "REC - Copa do Nordeste 2025.md"
  - REC – Copa Verde 2025: "REC - Copa Verde 2025.md"
  - REC – Supercopa do Brasil 2025: "REC - SUPERCOPA DO BRASIL 2025.md"
  - REC Revisão 1 – Feminino A1 2025: "REC Revisao 1 - Brasileiro Feminino A1 2025.md"
  - REC Revisão 1 – Feminino A2 2025: "REC Revisao 1 - Brasileiro Feminino A2 2025.md"
  - REC Compilado Final 2025: "REC_Compilado_Final_2025.md"
  - REC Fem & Base Compilado 2025: "REC_Fem&Base_2025_Compilado.md"
  - REC Masc 2025: "REC_Masc_2025.md"
  - REC Geral: "REC.md"
  - Regras de Futebol 2019-2020: "Regras de Futebol 2019-2020.md"
  - RGC 2025: "RGC 2025.md"
  - RNC – Ranking Nacional dos Clubes 2025: "RNC - Ranking Nacional dos Clubes 2025.md"
  - RNC FF 2025 – Ranking Feminino: "RNC FF 2025 - Ranking Nacional dos Clubes do Futebol Feminino.md"
  - RNF – Ranking Nacional das Federações 2025: "RNF - Ranking Nacional das Federacoes 2025.md"
  - RNF FF 2025 – Ranking Feminino Nacional: "FF 2025 - Ranking Nacional das Federacoes Estaduais do Futebol Feminino.md"









